# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Smarty
                                 A QGIS plugin
 Smarty attempt
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-01-19
        copyright            : (C) 2022 by Smarty
        email                : osgeo-it@smarty.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""
import pip

# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Smarty class from file Smarty.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """

    # try:
    #     import subprocess
    #     import sys
    #     import pip

    #     subprocess.check_call([sys.executable, "-m", "pip", "install", 'smartystreets_python_sdk'])
    # except:
    #     iface.messageBar().pushMessage("Error")

    import subprocess
    import sys
    import pip
    
    install('smartystreets_python_sdk')
    
    from .smarty import Smarty

    return Smarty(iface)

def install(package):
    if hasattr(pip, 'main'):
        pip.main(['install', package])
    else:
        pip._internal.main(['install', package])
