# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Smarty
                                 A QGIS plugin
 Smarty attempt
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-01-19
        copyright            : (C) 2022 by Smarty
        email                : osgeo-it@smarty.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""
import subprocess
import platform
import os

# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Smarty class from file Smarty.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    
    from .smarty import Smarty

    return Smarty(iface)


