# -*- coding: utf-8 -*-
"""
/***************************************************************************
 SmartyDialog
                                 A QGIS plugin
 Smarty attempt
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-01-19
        git sha              : $Format:%H$
        copyright            : (C) 2022 by Smarty
        email                : caroline@smarty.com
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *
from PyQt5.QtCore import *

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'smarty_dialog_base.ui'))


class SmartyDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None):
        """Constructor."""
        super(SmartyDialog, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)

    def closeEvent(self, event):

        self.save_dlg = QDialog()
        self.save_dlg.setWindowTitle("ALERT")

        title = QLabel("WARNING:", self.save_dlg)
        title.setFont(QFont("Helvetica",weight=QFont.Bold))
        title.setGeometry(10,10,100,10)

        #TODO: Should we add a QFrame so that it looks a little better?
        
        message = QLabel("Information currently is contained on a temporary memory layer. Please make your layer permanent before you close QGIS.", self.save_dlg)
        message.setGeometry(20,20, 200, 100)
        message.setWordWrap(True)

        self.save_dlg.show()


FORM_CLASS_, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'smarty_dialog_base.ui'))

class SaveDialog(QtWidgets.QDialog, FORM_CLASS_):
    def __init__(self, parent=None):
        super(SaveDialog, self).__init__(parent)
        self.setupUi(self)
